plugins {
    id 'fabric-loom' version '1.14.10'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

extensions {
    loom {
        minecraftVersion = '1.21.11'
        mappingsVersion = '1.21.11+build.5'
        run {
            version = 'client'
            propertyMap {
                property 'fabric-api' version '0.141.4+1.21.11'
            }
        }
    }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.11'
    mappings 'net.fabricmc:yarn:1.21.11+build.5:v2'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.141.4+1.21.11'
    include 'com.google.code.gson:gson:2.10.1'
}

processResources {
    inputs.property 'version', project.version
    from(sourceSets.main.resources.srcDirs) {
        include 'fabric.mod.json'
        expand [project: project]
    }
    into 'build/resources/main'
}
